# Site Settings
locale               : "pt-BR"
title                : "Edgardo Correa"
title_separator      : "-"
name                 : "Edgardo Correa"
description          : "Analista de Sistemas de Informação"
url                  : "https://edgardocorrea.github.io"
baseurl              : "" # Deixe em branco
repository           : "edgardocorrea/edgardo-correa.github.io"

# Seus dados
author:
  name             : "Edgardo Correa"
  avatar           : "/assets/images/bio-photo.jpg" # adicionar sua foto depois
  bio              : "Profissional formado em Sistemas da Informação, com foco em infraestrutura de redes, automação e segurança."
  location         : "São Paulo, São Paulo"
  email            : "edgardo.correa@email.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/edgardocorrea"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/edgardocorrea"
    - label: "Credly"
      icon: "fas fa-fw fa-certificate" # Ícone de certificado
      url: "https://www.credly.com/users/edgardo.correa/badges"

# Portfolio
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

# Aparência do Tema
minimal_mistakes_skin    : "contrast" # Opções: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise". Teste as que mais gostar!
